apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: phi3hblj4-python 
  janus-idp.io/tekton: phi3hblj4-python
  backstage.io/kubernetes-id: phi3hblj4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: phi3hblj4-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  