apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: phi3hblj4-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:5864c3512cfa77b81d185c198bf42e7dd620c099@sha256:861c7593d9c08cb3cba6383fb6036e41b3c7cb57ef067ddb9aa44ae8be306b75
          name: container-image
